spring:
  profiles:
    active: local
  thymeleaf:
    cache: false
    mode: HTML5
    suffix: .html

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
---

spring:
  redis:
    host: localhost
    port: 6379
  config:
    activate:
      on-profile: local


